# ===========================================
# Docker Compose - Infrastructure Template
# ===========================================
# 1. Copiez ce template pour votre client
# 2. Ajoutez vos services selon les besoins
# 3. Configurez les variables dans .env

version: '3.8'

services:
  # ========================================
  # Ajoutez vos services ici
  # ========================================
  
  # Voir examples/docker-compose.examples.yml pour des exemples

volumes:
  # ========================================
  # Définissez vos volumes ici
  # ========================================