services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      N8N_HOST: n8n.larefonte.store
      WEBHOOK_URL: https://n8n.larefonte.store/
      WEBHOOK_TUNNEL_URL: https://n8n.larefonte.store/
      VUE_APP_URL_BASE_API: https://n8n.larefonte.store/
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      GENERIC_TIMEZONE: Europe/Paris
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: ${N8N_PASSWORD}
      N8N_PUSH_BACKEND: websocket
      N8N_SECURE_COOKIE: "true"
      N8N_RUNNERS_ENABLED: "true"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: "true"
      MCP_OPENAPI_MCP_HEADERS: '{"Authorization": "Bearer ${NOTION_API_TOKEN}", "Notion-Version": "2022-06-28"}'
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n

  scraping-backend:
    build:
      context: /root/projects/shared/scraping-backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:5900:5900"
    environment:
      GOOGLE_CONTACT_PASSWORD: ${GOOGLE_CONTACT_PASSWORD}
      RANKERFOX_PASSWORD: ${RANKERFOX_PASSWORD}
      NODE_ENV: production
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      DATA_DIR: /usr/src/app/dist/data/navigators
    working_dir: /usr/src/app
    env_file:
      - .env 
    volumes:
      - scraping_backend_data:/usr/src/app/dist/data/navigators

  novnc:
    build:
      context: /root/projects/shared/novnc
      dockerfile: Dockerfile
    platform: linux/arm64
    container_name: novnc
    restart: always
    ports:
      - "127.0.0.1:6080:6080"
    environment:
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=900
      - DISPLAY_DEPTH=24
      - VNC_SERVER=scraping-backend:5900
    depends_on:
      - scraping-backend
      
  cercle-des-voyages-backend:
    build:
      context: /root/projects/external/Dashboard-Cercle-des-Voyages/backend/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3001:3001"
    env_file:
      - /root/projects/external/Dashboard-Cercle-des-Voyages/backend/.env

volumes:
  n8n_data:
    external: true
    name: project-n8n_n8n_data
  scraping_backend_data:
    external: true
    name: project-n8n_scraping-backend_data
